@baseUrl = http://localhost:9000
@basic = SDEyZV9ZUlBuTEZMSE1ZcTpJUFNHLVliRERKNENfdHNjRC1PdVlmcmZTbVZXOFVLVg==

### 获取访问令牌（Header Basic，grant_type在查询参数）
# @name issueTokenHeader
POST {{baseUrl}}/api/v1/oauth/token?grant_type=client_credentials
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{basic}}

### 获取访问令牌（URL 参数：Basic + base64）
# @name issueTokenParamWithPrefix
POST {{baseUrl}}/api/v1/oauth/token?grant_type=client_credentials&access_token=Basic%20{{basic}}
Content-Type: application/x-www-form-urlencoded

### 获取访问令牌（URL 参数：仅 base64）
# @name issueTokenParamPure
POST {{baseUrl}}/api/v1/oauth/token?grant_type=client_credentials&access_token={{basic}}
Content-Type: application/x-www-form-urlencoded

### 校验令牌（链式读取上一步 access_token）
# @name validateToken
POST {{baseUrl}}/api/v1/validate?token={{issueTokenHeader.response.body.$.access_token}}